### ISSUE TITLE
Missing file "server_information.py"

### ISSUE THREAD

**Issue by gxpyzgl** [SynergyLab-Cornell/codedbulk#1]
I try to run the implementation code following the given readme commands,  but didn't find the server_information.py file under WAN_exp_controller/core, and the link file seems broken.
![missing_server_information](https://user-images.githubusercontent.com/43445367/202615024-478d8aad-d817-469a-9add-074939a5fc44.png)
![broken_link](https://user-images.githubusercontent.com/43445367/202615222-b767417e-5d47-4efc-b01f-027aab91e246.png)

**Comment by shih-hao-tseng** [comment]
Thanks for reaching out. As specified in the README, we need to modify (actually create the file when necessary) server_information.py in step 4. The content of the file could be inferred from the codes, and it was deliberately ignored by git to avoid accidentally leaking the account and password information of the servers. I have added the template file to the repository so that we could explicitly see what we should include in the file. In case you have your own version, please remember to remove the file from git tracking to avoid leaking your server info.
